version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sampledb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
      # ./init.sql -> This is a file on your host machine (your local system). It should be present in the same folder as your docker-compose.yml.
      # /docker-entrypoint-initdb.d/init.sql -> This is the location inside the PostgreSQL container where it expects .sql files during initial setup.
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"

  backend:
    build: ./backend
    container_name: flask-backend
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
